//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SistZP2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Больничный лист.
    /// </summary>
    // *** Start programmer edit section *** (БольнЛист CustomAttributes)

    // *** End programmer edit section *** (БольнЛист CustomAttributes)
    [AutoAltered()]
    [Caption("Больничный лист")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БольнЛистE", new string[] {
            "НомерДок as \'Номер документа\'",
            "ДатаНачБол as \'Дата начала больничного\'",
            "ДатаОконБол as \'Дата окончания больничного\'",
            "КолДней as \'Количество дней\'",
            "Первичный as \'Первичный\'",
            "Повторный as \'Повторный\'",
            "Причина as \'Причина \'",
            "ЗаСчетРаб as \'За счет работ\'",
            "ЗаСчетФСС as \'За счет ФСС\'",
            "ВсегоНачисл as \'Всего начислений\'"})]
    public class БольнЛист : ICSSoft.STORMNET.DataObject
    {
        
        private double fЗаСчетФСС;
        
        private double fВсегоНачисл;
        
        private System.DateTime fДатаОконБол;
        
        private System.DateTime fДатаНачБол;
        
        private int fНомерДок;
        
        private int fКолДней;
        
        private bool fПовторный = false;
        
        private bool fПервичный = false;
        
        private IIS.SistZP2.ПричНетр fПричина;
        
        private double fЗаСчетРаб;
        
        private IIS.SistZP2.РасчетныйЛист fРасчетныйЛист;
        
        // *** Start programmer edit section *** (БольнЛист CustomMembers)

        // *** End programmer edit section *** (БольнЛист CustomMembers)

        
        /// <summary>
        /// ВсегоНачисл.
        /// </summary>
        // *** Start programmer edit section *** (БольнЛист.ВсегоНачисл CustomAttributes)

        // *** End programmer edit section *** (БольнЛист.ВсегоНачисл CustomAttributes)
        public virtual double ВсегоНачисл
        {
            get
            {
                // *** Start programmer edit section *** (БольнЛист.ВсегоНачисл Get start)

                // *** End programmer edit section *** (БольнЛист.ВсегоНачисл Get start)
                double result = this.fВсегоНачисл;
                // *** Start programmer edit section *** (БольнЛист.ВсегоНачисл Get end)

                // *** End programmer edit section *** (БольнЛист.ВсегоНачисл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БольнЛист.ВсегоНачисл Set start)

                // *** End programmer edit section *** (БольнЛист.ВсегоНачисл Set start)
                this.fВсегоНачисл = value;
                // *** Start programmer edit section *** (БольнЛист.ВсегоНачисл Set end)

                // *** End programmer edit section *** (БольнЛист.ВсегоНачисл Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачБол.
        /// </summary>
        // *** Start programmer edit section *** (БольнЛист.ДатаНачБол CustomAttributes)

        // *** End programmer edit section *** (БольнЛист.ДатаНачБол CustomAttributes)
        public virtual System.DateTime ДатаНачБол
        {
            get
            {
                // *** Start programmer edit section *** (БольнЛист.ДатаНачБол Get start)

                // *** End programmer edit section *** (БольнЛист.ДатаНачБол Get start)
                System.DateTime result = this.fДатаНачБол;
                // *** Start programmer edit section *** (БольнЛист.ДатаНачБол Get end)

                // *** End programmer edit section *** (БольнЛист.ДатаНачБол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БольнЛист.ДатаНачБол Set start)

                // *** End programmer edit section *** (БольнЛист.ДатаНачБол Set start)
                this.fДатаНачБол = value;
                // *** Start programmer edit section *** (БольнЛист.ДатаНачБол Set end)

                // *** End programmer edit section *** (БольнЛист.ДатаНачБол Set end)
            }
        }
        
        /// <summary>
        /// ДатаОконБол.
        /// </summary>
        // *** Start programmer edit section *** (БольнЛист.ДатаОконБол CustomAttributes)

        // *** End programmer edit section *** (БольнЛист.ДатаОконБол CustomAttributes)
        public virtual System.DateTime ДатаОконБол
        {
            get
            {
                // *** Start programmer edit section *** (БольнЛист.ДатаОконБол Get start)

                // *** End programmer edit section *** (БольнЛист.ДатаОконБол Get start)
                System.DateTime result = this.fДатаОконБол;
                // *** Start programmer edit section *** (БольнЛист.ДатаОконБол Get end)

                // *** End programmer edit section *** (БольнЛист.ДатаОконБол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БольнЛист.ДатаОконБол Set start)

                // *** End programmer edit section *** (БольнЛист.ДатаОконБол Set start)
                this.fДатаОконБол = value;
                // *** Start programmer edit section *** (БольнЛист.ДатаОконБол Set end)

                // *** End programmer edit section *** (БольнЛист.ДатаОконБол Set end)
            }
        }
        
        /// <summary>
        /// ЗаСчетРаб.
        /// </summary>
        // *** Start programmer edit section *** (БольнЛист.ЗаСчетРаб CustomAttributes)

        // *** End programmer edit section *** (БольнЛист.ЗаСчетРаб CustomAttributes)
        public virtual double ЗаСчетРаб
        {
            get
            {
                // *** Start programmer edit section *** (БольнЛист.ЗаСчетРаб Get start)

                // *** End programmer edit section *** (БольнЛист.ЗаСчетРаб Get start)
                double result = this.fЗаСчетРаб;
                // *** Start programmer edit section *** (БольнЛист.ЗаСчетРаб Get end)

                // *** End programmer edit section *** (БольнЛист.ЗаСчетРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БольнЛист.ЗаСчетРаб Set start)

                // *** End programmer edit section *** (БольнЛист.ЗаСчетРаб Set start)
                this.fЗаСчетРаб = value;
                // *** Start programmer edit section *** (БольнЛист.ЗаСчетРаб Set end)

                // *** End programmer edit section *** (БольнЛист.ЗаСчетРаб Set end)
            }
        }
        
        /// <summary>
        /// ЗаСчетФСС.
        /// </summary>
        // *** Start programmer edit section *** (БольнЛист.ЗаСчетФСС CustomAttributes)

        // *** End programmer edit section *** (БольнЛист.ЗаСчетФСС CustomAttributes)
        public virtual double ЗаСчетФСС
        {
            get
            {
                // *** Start programmer edit section *** (БольнЛист.ЗаСчетФСС Get start)

                // *** End programmer edit section *** (БольнЛист.ЗаСчетФСС Get start)
                double result = this.fЗаСчетФСС;
                // *** Start programmer edit section *** (БольнЛист.ЗаСчетФСС Get end)

                // *** End programmer edit section *** (БольнЛист.ЗаСчетФСС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БольнЛист.ЗаСчетФСС Set start)

                // *** End programmer edit section *** (БольнЛист.ЗаСчетФСС Set start)
                this.fЗаСчетФСС = value;
                // *** Start programmer edit section *** (БольнЛист.ЗаСчетФСС Set end)

                // *** End programmer edit section *** (БольнЛист.ЗаСчетФСС Set end)
            }
        }
        
        /// <summary>
        /// КолДней.
        /// </summary>
        // *** Start programmer edit section *** (БольнЛист.КолДней CustomAttributes)

        // *** End programmer edit section *** (БольнЛист.КолДней CustomAttributes)
        public virtual int КолДней
        {
            get
            {
                // *** Start programmer edit section *** (БольнЛист.КолДней Get start)

                // *** End programmer edit section *** (БольнЛист.КолДней Get start)
                int result = this.fКолДней;
                // *** Start programmer edit section *** (БольнЛист.КолДней Get end)

                // *** End programmer edit section *** (БольнЛист.КолДней Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БольнЛист.КолДней Set start)

                // *** End programmer edit section *** (БольнЛист.КолДней Set start)
                this.fКолДней = value;
                // *** Start programmer edit section *** (БольнЛист.КолДней Set end)

                // *** End programmer edit section *** (БольнЛист.КолДней Set end)
            }
        }
        
        /// <summary>
        /// НомерДок.
        /// </summary>
        // *** Start programmer edit section *** (БольнЛист.НомерДок CustomAttributes)

        // *** End programmer edit section *** (БольнЛист.НомерДок CustomAttributes)
        public virtual int НомерДок
        {
            get
            {
                // *** Start programmer edit section *** (БольнЛист.НомерДок Get start)

                // *** End programmer edit section *** (БольнЛист.НомерДок Get start)
                int result = this.fНомерДок;
                // *** Start programmer edit section *** (БольнЛист.НомерДок Get end)

                // *** End programmer edit section *** (БольнЛист.НомерДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БольнЛист.НомерДок Set start)

                // *** End programmer edit section *** (БольнЛист.НомерДок Set start)
                this.fНомерДок = value;
                // *** Start programmer edit section *** (БольнЛист.НомерДок Set end)

                // *** End programmer edit section *** (БольнЛист.НомерДок Set end)
            }
        }
        
        /// <summary>
        /// Первичный.
        /// </summary>
        // *** Start programmer edit section *** (БольнЛист.Первичный CustomAttributes)

        // *** End programmer edit section *** (БольнЛист.Первичный CustomAttributes)
        public virtual bool Первичный
        {
            get
            {
                // *** Start programmer edit section *** (БольнЛист.Первичный Get start)

                // *** End programmer edit section *** (БольнЛист.Первичный Get start)
                bool result = this.fПервичный;
                // *** Start programmer edit section *** (БольнЛист.Первичный Get end)

                // *** End programmer edit section *** (БольнЛист.Первичный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БольнЛист.Первичный Set start)

                // *** End programmer edit section *** (БольнЛист.Первичный Set start)
                this.fПервичный = value;
                // *** Start programmer edit section *** (БольнЛист.Первичный Set end)

                // *** End programmer edit section *** (БольнЛист.Первичный Set end)
            }
        }
        
        /// <summary>
        /// Повторный.
        /// </summary>
        // *** Start programmer edit section *** (БольнЛист.Повторный CustomAttributes)

        // *** End programmer edit section *** (БольнЛист.Повторный CustomAttributes)
        public virtual bool Повторный
        {
            get
            {
                // *** Start programmer edit section *** (БольнЛист.Повторный Get start)

                // *** End programmer edit section *** (БольнЛист.Повторный Get start)
                bool result = this.fПовторный;
                // *** Start programmer edit section *** (БольнЛист.Повторный Get end)

                // *** End programmer edit section *** (БольнЛист.Повторный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БольнЛист.Повторный Set start)

                // *** End programmer edit section *** (БольнЛист.Повторный Set start)
                this.fПовторный = value;
                // *** Start programmer edit section *** (БольнЛист.Повторный Set end)

                // *** End programmer edit section *** (БольнЛист.Повторный Set end)
            }
        }
        
        /// <summary>
        /// Причина.
        /// </summary>
        // *** Start programmer edit section *** (БольнЛист.Причина CustomAttributes)

        // *** End programmer edit section *** (БольнЛист.Причина CustomAttributes)
        public virtual IIS.SistZP2.ПричНетр Причина
        {
            get
            {
                // *** Start programmer edit section *** (БольнЛист.Причина Get start)

                // *** End programmer edit section *** (БольнЛист.Причина Get start)
                IIS.SistZP2.ПричНетр result = this.fПричина;
                // *** Start programmer edit section *** (БольнЛист.Причина Get end)

                // *** End programmer edit section *** (БольнЛист.Причина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БольнЛист.Причина Set start)

                // *** End programmer edit section *** (БольнЛист.Причина Set start)
                this.fПричина = value;
                // *** Start programmer edit section *** (БольнЛист.Причина Set end)

                // *** End programmer edit section *** (БольнЛист.Причина Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.SistZP2.РасчетныйЛист.
        /// </summary>
        // *** Start programmer edit section *** (БольнЛист.РасчетныйЛист CustomAttributes)

        // *** End programmer edit section *** (БольнЛист.РасчетныйЛист CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасчетныйЛист"})]
        public virtual IIS.SistZP2.РасчетныйЛист РасчетныйЛист
        {
            get
            {
                // *** Start programmer edit section *** (БольнЛист.РасчетныйЛист Get start)

                // *** End programmer edit section *** (БольнЛист.РасчетныйЛист Get start)
                IIS.SistZP2.РасчетныйЛист result = this.fРасчетныйЛист;
                // *** Start programmer edit section *** (БольнЛист.РасчетныйЛист Get end)

                // *** End programmer edit section *** (БольнЛист.РасчетныйЛист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БольнЛист.РасчетныйЛист Set start)

                // *** End programmer edit section *** (БольнЛист.РасчетныйЛист Set start)
                this.fРасчетныйЛист = value;
                // *** Start programmer edit section *** (БольнЛист.РасчетныйЛист Set end)

                // *** End programmer edit section *** (БольнЛист.РасчетныйЛист Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БольнЛистE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БольнЛистE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БольнЛистE", typeof(IIS.SistZP2.БольнЛист));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of БольнЛист.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfБольнЛист CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfБольнЛист CustomAttributes)
    public class DetailArrayOfБольнЛист : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.SistZP2.DetailArrayOfБольнЛист members)

        // *** End programmer edit section *** (IIS.SistZP2.DetailArrayOfБольнЛист members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type БольнЛист by index.
        /// </summary>
        /// <summary>
        /// Adds object with type БольнЛист.
        /// </summary>
        public DetailArrayOfБольнЛист(IIS.SistZP2.РасчетныйЛист fРасчетныйЛист) : 
                base(typeof(БольнЛист), ((ICSSoft.STORMNET.DataObject)(fРасчетныйЛист)))
        {
        }
        
        public IIS.SistZP2.БольнЛист this[int index]
        {
            get
            {
                return ((IIS.SistZP2.БольнЛист)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.SistZP2.БольнЛист dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
