//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SistZP2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вычет.
    /// </summary>
    // *** Start programmer edit section *** (Вычет CustomAttributes)

    // *** End programmer edit section *** (Вычет CustomAttributes)
    public enum Вычет
    {
        
        // *** Start programmer edit section *** (Вычет.НДФЛ CustomAttributes)

        // *** End programmer edit section *** (Вычет.НДФЛ CustomAttributes)
        [Caption("НДФЛ")]
        НДФЛ,
        
        // *** Start programmer edit section *** (Вычет.Штраф CustomAttributes)

        // *** End programmer edit section *** (Вычет.Штраф CustomAttributes)
        [Caption("Штраф")]
        Штраф,
        
        // *** Start programmer edit section *** (Вычет.ВозмещМатУщ CustomAttributes)

        // *** End programmer edit section *** (Вычет.ВозмещМатУщ CustomAttributes)
        [Caption("Возмещение материального ущерба")]
        ВозмещМатУщ,
        
        // *** Start programmer edit section *** (Вычет.ВПенсФонд CustomAttributes)

        // *** End programmer edit section *** (Вычет.ВПенсФонд CustomAttributes)
        [Caption("В пенсионный фонд")]
        ВПенсФонд,
        
        // *** Start programmer edit section *** (Вычет.СтрахВыч CustomAttributes)

        // *** End programmer edit section *** (Вычет.СтрахВыч CustomAttributes)
        [Caption("Страховые вычеты")]
        СтрахВыч,
        
        // *** Start programmer edit section *** (Вычет.ВозврАвнаса CustomAttributes)

        // *** End programmer edit section *** (Вычет.ВозврАвнаса CustomAttributes)
        [Caption("Возврат аванса")]
        ВозврАвнаса,
    }
}
