//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SistZP2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Критер прем.
    /// </summary>
    // *** Start programmer edit section *** (КритерПрем CustomAttributes)

    // *** End programmer edit section *** (КритерПрем CustomAttributes)
    public enum КритерПрем
    {
        
        // *** Start programmer edit section *** (КритерПрем.ВыполЗадВСр CustomAttributes)

        // *** End programmer edit section *** (КритерПрем.ВыполЗадВСр CustomAttributes)
        [Caption("Выполнено задание в срок")]
        ВыполЗадВСр,
        
        // *** Start programmer edit section *** (КритерПрем.СдачаОтчВСр CustomAttributes)

        // *** End programmer edit section *** (КритерПрем.СдачаОтчВСр CustomAttributes)
        [Caption("Сдача отчета в срок")]
        СдачаОтчВСр,
        
        // *** Start programmer edit section *** (КритерПрем.ЗаслПерПред CustomAttributes)

        // *** End programmer edit section *** (КритерПрем.ЗаслПерПред CustomAttributes)
        [Caption("Заслуги перед предприятием")]
        ЗаслПерПред,
    }
}
