//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SistZP2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Организации.
    /// </summary>
    // *** Start programmer edit section *** (Организации CustomAttributes)

    // *** End programmer edit section *** (Организации CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОрганизацииE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "ОГРН as \'ОГРН\'",
            "Адрес as \'Адрес\'"})]
    [View("ОрганизацииL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "ОГРН as \'ОГРН\'",
            "Адрес as \'Адрес\'"})]
    public class Организации : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private int fКод;
        
        private int fКПП;
        
        private int fИНН;
        
        private int fОГРН;
        
        private string fАдрес;
        
        // *** Start programmer edit section *** (Организации CustomMembers)

        // *** End programmer edit section *** (Организации CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Организации.Адрес CustomAttributes)

        // *** End programmer edit section *** (Организации.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Организации.Адрес Get start)

                // *** End programmer edit section *** (Организации.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Организации.Адрес Get end)

                // *** End programmer edit section *** (Организации.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.Адрес Set start)

                // *** End programmer edit section *** (Организации.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Организации.Адрес Set end)

                // *** End programmer edit section *** (Организации.Адрес Set end)
            }
        }
        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (Организации.ИНН CustomAttributes)

        // *** End programmer edit section *** (Организации.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (Организации.ИНН Get start)

                // *** End programmer edit section *** (Организации.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (Организации.ИНН Get end)

                // *** End programmer edit section *** (Организации.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.ИНН Set start)

                // *** End programmer edit section *** (Организации.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (Организации.ИНН Set end)

                // *** End programmer edit section *** (Организации.ИНН Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Организации.Код CustomAttributes)

        // *** End programmer edit section *** (Организации.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Организации.Код Get start)

                // *** End programmer edit section *** (Организации.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Организации.Код Get end)

                // *** End programmer edit section *** (Организации.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.Код Set start)

                // *** End programmer edit section *** (Организации.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Организации.Код Set end)

                // *** End programmer edit section *** (Организации.Код Set end)
            }
        }
        
        /// <summary>
        /// КПП.
        /// </summary>
        // *** Start programmer edit section *** (Организации.КПП CustomAttributes)

        // *** End programmer edit section *** (Организации.КПП CustomAttributes)
        public virtual int КПП
        {
            get
            {
                // *** Start programmer edit section *** (Организации.КПП Get start)

                // *** End programmer edit section *** (Организации.КПП Get start)
                int result = this.fКПП;
                // *** Start programmer edit section *** (Организации.КПП Get end)

                // *** End programmer edit section *** (Организации.КПП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.КПП Set start)

                // *** End programmer edit section *** (Организации.КПП Set start)
                this.fКПП = value;
                // *** Start programmer edit section *** (Организации.КПП Set end)

                // *** End programmer edit section *** (Организации.КПП Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Организации.Наименование CustomAttributes)

        // *** End programmer edit section *** (Организации.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Организации.Наименование Get start)

                // *** End programmer edit section *** (Организации.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Организации.Наименование Get end)

                // *** End programmer edit section *** (Организации.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.Наименование Set start)

                // *** End programmer edit section *** (Организации.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Организации.Наименование Set end)

                // *** End programmer edit section *** (Организации.Наименование Set end)
            }
        }
        
        /// <summary>
        /// ОГРН.
        /// </summary>
        // *** Start programmer edit section *** (Организации.ОГРН CustomAttributes)

        // *** End programmer edit section *** (Организации.ОГРН CustomAttributes)
        public virtual int ОГРН
        {
            get
            {
                // *** Start programmer edit section *** (Организации.ОГРН Get start)

                // *** End programmer edit section *** (Организации.ОГРН Get start)
                int result = this.fОГРН;
                // *** Start programmer edit section *** (Организации.ОГРН Get end)

                // *** End programmer edit section *** (Организации.ОГРН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организации.ОГРН Set start)

                // *** End programmer edit section *** (Организации.ОГРН Set start)
                this.fОГРН = value;
                // *** Start programmer edit section *** (Организации.ОГРН Set end)

                // *** End programmer edit section *** (Организации.ОГРН Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОрганизацииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацииE", typeof(IIS.SistZP2.Организации));
                }
            }
            
            /// <summary>
            /// "ОрганизацииL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацииL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацииL", typeof(IIS.SistZP2.Организации));
                }
            }
        }
    }
}
