//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SistZP2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отпускной лист.
    /// </summary>
    // *** Start programmer edit section *** (Отпуск CustomAttributes)

    // *** End programmer edit section *** (Отпуск CustomAttributes)
    [AutoAltered()]
    [Caption("Отпускной лист")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтпускE", new string[] {
            "НомерДок as \'Номер документа\'",
            "ДатаНачОтп as \'Дата начала отпуска\'",
            "ДатаОконОтп as \'Дата окончания отпуска\'",
            "КолДней as \'Количество дней\'"})]
    public class Отпуск : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаНачОтп;
        
        private int fНомерДок;
        
        private System.DateTime fДатаОконОтп;
        
        private int fКолДней;
        
        private IIS.SistZP2.РасчетныйЛист fРасчетныйЛист;
        
        // *** Start programmer edit section *** (Отпуск CustomMembers)

        // *** End programmer edit section *** (Отпуск CustomMembers)

        
        /// <summary>
        /// ДатаНачОтп.
        /// </summary>
        // *** Start programmer edit section *** (Отпуск.ДатаНачОтп CustomAttributes)

        // *** End programmer edit section *** (Отпуск.ДатаНачОтп CustomAttributes)
        public virtual System.DateTime ДатаНачОтп
        {
            get
            {
                // *** Start programmer edit section *** (Отпуск.ДатаНачОтп Get start)

                // *** End programmer edit section *** (Отпуск.ДатаНачОтп Get start)
                System.DateTime result = this.fДатаНачОтп;
                // *** Start programmer edit section *** (Отпуск.ДатаНачОтп Get end)

                // *** End programmer edit section *** (Отпуск.ДатаНачОтп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отпуск.ДатаНачОтп Set start)

                // *** End programmer edit section *** (Отпуск.ДатаНачОтп Set start)
                this.fДатаНачОтп = value;
                // *** Start programmer edit section *** (Отпуск.ДатаНачОтп Set end)

                // *** End programmer edit section *** (Отпуск.ДатаНачОтп Set end)
            }
        }
        
        /// <summary>
        /// ДатаОконОтп.
        /// </summary>
        // *** Start programmer edit section *** (Отпуск.ДатаОконОтп CustomAttributes)

        // *** End programmer edit section *** (Отпуск.ДатаОконОтп CustomAttributes)
        public virtual System.DateTime ДатаОконОтп
        {
            get
            {
                // *** Start programmer edit section *** (Отпуск.ДатаОконОтп Get start)

                // *** End programmer edit section *** (Отпуск.ДатаОконОтп Get start)
                System.DateTime result = this.fДатаОконОтп;
                // *** Start programmer edit section *** (Отпуск.ДатаОконОтп Get end)

                // *** End programmer edit section *** (Отпуск.ДатаОконОтп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отпуск.ДатаОконОтп Set start)

                // *** End programmer edit section *** (Отпуск.ДатаОконОтп Set start)
                this.fДатаОконОтп = value;
                // *** Start programmer edit section *** (Отпуск.ДатаОконОтп Set end)

                // *** End programmer edit section *** (Отпуск.ДатаОконОтп Set end)
            }
        }
        
        /// <summary>
        /// КолДней.
        /// </summary>
        // *** Start programmer edit section *** (Отпуск.КолДней CustomAttributes)

        // *** End programmer edit section *** (Отпуск.КолДней CustomAttributes)
        public virtual int КолДней
        {
            get
            {
                // *** Start programmer edit section *** (Отпуск.КолДней Get start)

                // *** End programmer edit section *** (Отпуск.КолДней Get start)
                int result = this.fКолДней;
                // *** Start programmer edit section *** (Отпуск.КолДней Get end)

                // *** End programmer edit section *** (Отпуск.КолДней Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отпуск.КолДней Set start)

                // *** End programmer edit section *** (Отпуск.КолДней Set start)
                this.fКолДней = value;
                // *** Start programmer edit section *** (Отпуск.КолДней Set end)

                // *** End programmer edit section *** (Отпуск.КолДней Set end)
            }
        }
        
        /// <summary>
        /// НомерДок.
        /// </summary>
        // *** Start programmer edit section *** (Отпуск.НомерДок CustomAttributes)

        // *** End programmer edit section *** (Отпуск.НомерДок CustomAttributes)
        public virtual int НомерДок
        {
            get
            {
                // *** Start programmer edit section *** (Отпуск.НомерДок Get start)

                // *** End programmer edit section *** (Отпуск.НомерДок Get start)
                int result = this.fНомерДок;
                // *** Start programmer edit section *** (Отпуск.НомерДок Get end)

                // *** End programmer edit section *** (Отпуск.НомерДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отпуск.НомерДок Set start)

                // *** End programmer edit section *** (Отпуск.НомерДок Set start)
                this.fНомерДок = value;
                // *** Start programmer edit section *** (Отпуск.НомерДок Set end)

                // *** End programmer edit section *** (Отпуск.НомерДок Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.SistZP2.РасчетныйЛист.
        /// </summary>
        // *** Start programmer edit section *** (Отпуск.РасчетныйЛист CustomAttributes)

        // *** End programmer edit section *** (Отпуск.РасчетныйЛист CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасчетныйЛист"})]
        public virtual IIS.SistZP2.РасчетныйЛист РасчетныйЛист
        {
            get
            {
                // *** Start programmer edit section *** (Отпуск.РасчетныйЛист Get start)

                // *** End programmer edit section *** (Отпуск.РасчетныйЛист Get start)
                IIS.SistZP2.РасчетныйЛист result = this.fРасчетныйЛист;
                // *** Start programmer edit section *** (Отпуск.РасчетныйЛист Get end)

                // *** End programmer edit section *** (Отпуск.РасчетныйЛист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отпуск.РасчетныйЛист Set start)

                // *** End programmer edit section *** (Отпуск.РасчетныйЛист Set start)
                this.fРасчетныйЛист = value;
                // *** Start programmer edit section *** (Отпуск.РасчетныйЛист Set end)

                // *** End programmer edit section *** (Отпуск.РасчетныйЛист Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтпускE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтпускE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтпускE", typeof(IIS.SistZP2.Отпуск));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Отпуск.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОтпуск CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОтпуск CustomAttributes)
    public class DetailArrayOfОтпуск : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.SistZP2.DetailArrayOfОтпуск members)

        // *** End programmer edit section *** (IIS.SistZP2.DetailArrayOfОтпуск members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Отпуск by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Отпуск.
        /// </summary>
        public DetailArrayOfОтпуск(IIS.SistZP2.РасчетныйЛист fРасчетныйЛист) : 
                base(typeof(Отпуск), ((ICSSoft.STORMNET.DataObject)(fРасчетныйЛист)))
        {
        }
        
        public IIS.SistZP2.Отпуск this[int index]
        {
            get
            {
                return ((IIS.SistZP2.Отпуск)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.SistZP2.Отпуск dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
