//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SistZP2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Премии.
    /// </summary>
    // *** Start programmer edit section *** (Премии CustomAttributes)

    // *** End programmer edit section *** (Премии CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПремииE", new string[] {
            "Критерий as \'Критерий\'",
            "Сумма as \'Сумма\'"})]
    public class Премии : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.SistZP2.КритерПрем fКритерий;
        
        private double fСумма;
        
        private IIS.SistZP2.РасчетныйЛист fРасчетныйЛист;
        
        // *** Start programmer edit section *** (Премии CustomMembers)

        // *** End programmer edit section *** (Премии CustomMembers)

        
        /// <summary>
        /// Критерий.
        /// </summary>
        // *** Start programmer edit section *** (Премии.Критерий CustomAttributes)

        // *** End programmer edit section *** (Премии.Критерий CustomAttributes)
        public virtual IIS.SistZP2.КритерПрем Критерий
        {
            get
            {
                // *** Start programmer edit section *** (Премии.Критерий Get start)

                // *** End programmer edit section *** (Премии.Критерий Get start)
                IIS.SistZP2.КритерПрем result = this.fКритерий;
                // *** Start programmer edit section *** (Премии.Критерий Get end)

                // *** End programmer edit section *** (Премии.Критерий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Премии.Критерий Set start)

                // *** End programmer edit section *** (Премии.Критерий Set start)
                this.fКритерий = value;
                // *** Start programmer edit section *** (Премии.Критерий Set end)

                // *** End programmer edit section *** (Премии.Критерий Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Премии.Сумма CustomAttributes)

        // *** End programmer edit section *** (Премии.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Премии.Сумма Get start)

                // *** End programmer edit section *** (Премии.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Премии.Сумма Get end)

                // *** End programmer edit section *** (Премии.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Премии.Сумма Set start)

                // *** End programmer edit section *** (Премии.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Премии.Сумма Set end)

                // *** End programmer edit section *** (Премии.Сумма Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.SistZP2.РасчетныйЛист.
        /// </summary>
        // *** Start programmer edit section *** (Премии.РасчетныйЛист CustomAttributes)

        // *** End programmer edit section *** (Премии.РасчетныйЛист CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасчетныйЛист"})]
        public virtual IIS.SistZP2.РасчетныйЛист РасчетныйЛист
        {
            get
            {
                // *** Start programmer edit section *** (Премии.РасчетныйЛист Get start)

                // *** End programmer edit section *** (Премии.РасчетныйЛист Get start)
                IIS.SistZP2.РасчетныйЛист result = this.fРасчетныйЛист;
                // *** Start programmer edit section *** (Премии.РасчетныйЛист Get end)

                // *** End programmer edit section *** (Премии.РасчетныйЛист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Премии.РасчетныйЛист Set start)

                // *** End programmer edit section *** (Премии.РасчетныйЛист Set start)
                this.fРасчетныйЛист = value;
                // *** Start programmer edit section *** (Премии.РасчетныйЛист Set end)

                // *** End programmer edit section *** (Премии.РасчетныйЛист Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПремииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПремииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПремииE", typeof(IIS.SistZP2.Премии));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Премии.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПремии CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПремии CustomAttributes)
    public class DetailArrayOfПремии : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.SistZP2.DetailArrayOfПремии members)

        // *** End programmer edit section *** (IIS.SistZP2.DetailArrayOfПремии members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Премии by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Премии.
        /// </summary>
        public DetailArrayOfПремии(IIS.SistZP2.РасчетныйЛист fРасчетныйЛист) : 
                base(typeof(Премии), ((ICSSoft.STORMNET.DataObject)(fРасчетныйЛист)))
        {
        }
        
        public IIS.SistZP2.Премии this[int index]
        {
            get
            {
                return ((IIS.SistZP2.Премии)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.SistZP2.Премии dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
