//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SistZP2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Прич нетр.
    /// </summary>
    // *** Start programmer edit section *** (ПричНетр CustomAttributes)

    // *** End programmer edit section *** (ПричНетр CustomAttributes)
    public enum ПричНетр
    {
        
        // *** Start programmer edit section *** (ПричНетр.Заболев CustomAttributes)

        // *** End programmer edit section *** (ПричНетр.Заболев CustomAttributes)
        [Caption("Заболевание")]
        Заболев,
        
        // *** Start programmer edit section *** (ПричНетр.Травма CustomAttributes)

        // *** End programmer edit section *** (ПричНетр.Травма CustomAttributes)
        [Caption("Травма")]
        Травма,
        
        // *** Start programmer edit section *** (ПричНетр.ОтпускПоБер CustomAttributes)

        // *** End programmer edit section *** (ПричНетр.ОтпускПоБер CustomAttributes)
        [Caption("Отпуск по беременности")]
        ОтпускПоБер,
        
        // *** Start programmer edit section *** (ПричНетр.ТравмНаПрои CustomAttributes)

        // *** End programmer edit section *** (ПричНетр.ТравмНаПрои CustomAttributes)
        [Caption("Травма на производстве")]
        ТравмНаПрои,
        
        // *** Start programmer edit section *** (ПричНетр.УходЗаРеб CustomAttributes)

        // *** End programmer edit section *** (ПричНетр.УходЗаРеб CustomAttributes)
        [Caption("Уход за ребенком")]
        УходЗаРеб,
        
        // *** Start programmer edit section *** (ПричНетр.УхЗаБолРеб CustomAttributes)

        // *** End programmer edit section *** (ПричНетр.УхЗаБолРеб CustomAttributes)
        [Caption("Уход за ольным ребенком")]
        УхЗаБолРеб,
        
        // *** Start programmer edit section *** (ПричНетр.Карантин CustomAttributes)

        // *** End programmer edit section *** (ПричНетр.Карантин CustomAttributes)
        [Caption("Карантин")]
        Карантин,
    }
}
