//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SistZP2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "Код as \'Код\'",
            "ФИО as \'ФИО\'",
            "РабТел as \'Рабочий телефон\'",
            "Почта as \'Почта\'",
            "Оклад as \'Оклад\'",
            "ПроцСтавка as \'Процентная ставка\'",
            "Должности as \'Должность\'",
            "Отделы as \'Отдел\'",
            "Организации as \'Организация\'"})]
    [MasterViewDefineAttribute("СотрудникиE", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("СотрудникиE", "Отделы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("СотрудникиE", "Организации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("СотрудникиL", new string[] {
            "Код as \'Код\'",
            "ФИО as \'ФИО\'",
            "РабТел as \'Рабочий телефон\'",
            "Почта as \'Почта\'",
            "Оклад as \'Оклад\'",
            "ПроцСтавка as \'Процентная ставка\'",
            "Должности as \'Должность\'",
            "Отделы as \'Отдел\'",
            "Организации as \'Организация\'"})]
    [MasterViewDefineAttribute("СотрудникиL", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("СотрудникиL", "Отделы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("СотрудникиL", "Организации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private double fОклад;
        
        private string fПочта;
        
        private int fКод;
        
        private string fФИО;
        
        private double fПроцСтавка;
        
        private string fРабТел;
        
        private IIS.SistZP2.Организации fОрганизации;
        
        private IIS.SistZP2.Отделы fОтделы;
        
        private IIS.SistZP2.Должности fДолжности;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Код CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Код Get start)

                // *** End programmer edit section *** (Сотрудники.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Сотрудники.Код Get end)

                // *** End programmer edit section *** (Сотрудники.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Код Set start)

                // *** End programmer edit section *** (Сотрудники.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Сотрудники.Код Set end)

                // *** End programmer edit section *** (Сотрудники.Код Set end)
            }
        }
        
        /// <summary>
        /// Оклад.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Оклад CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Оклад CustomAttributes)
        public virtual double Оклад
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Оклад Get start)

                // *** End programmer edit section *** (Сотрудники.Оклад Get start)
                double result = this.fОклад;
                // *** Start programmer edit section *** (Сотрудники.Оклад Get end)

                // *** End programmer edit section *** (Сотрудники.Оклад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Оклад Set start)

                // *** End programmer edit section *** (Сотрудники.Оклад Set start)
                this.fОклад = value;
                // *** Start programmer edit section *** (Сотрудники.Оклад Set end)

                // *** End programmer edit section *** (Сотрудники.Оклад Set end)
            }
        }
        
        /// <summary>
        /// Почта.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Почта CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Почта CustomAttributes)
        [StrLen(255)]
        public virtual string Почта
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Почта Get start)

                // *** End programmer edit section *** (Сотрудники.Почта Get start)
                string result = this.fПочта;
                // *** Start programmer edit section *** (Сотрудники.Почта Get end)

                // *** End programmer edit section *** (Сотрудники.Почта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Почта Set start)

                // *** End programmer edit section *** (Сотрудники.Почта Set start)
                this.fПочта = value;
                // *** Start programmer edit section *** (Сотрудники.Почта Set end)

                // *** End programmer edit section *** (Сотрудники.Почта Set end)
            }
        }
        
        /// <summary>
        /// ПроцСтавка.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ПроцСтавка CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ПроцСтавка CustomAttributes)
        public virtual double ПроцСтавка
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ПроцСтавка Get start)

                // *** End programmer edit section *** (Сотрудники.ПроцСтавка Get start)
                double result = this.fПроцСтавка;
                // *** Start programmer edit section *** (Сотрудники.ПроцСтавка Get end)

                // *** End programmer edit section *** (Сотрудники.ПроцСтавка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ПроцСтавка Set start)

                // *** End programmer edit section *** (Сотрудники.ПроцСтавка Set start)
                this.fПроцСтавка = value;
                // *** Start programmer edit section *** (Сотрудники.ПроцСтавка Set end)

                // *** End programmer edit section *** (Сотрудники.ПроцСтавка Set end)
            }
        }
        
        /// <summary>
        /// РабТел.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.РабТел CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.РабТел CustomAttributes)
        [StrLen(255)]
        public virtual string РабТел
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.РабТел Get start)

                // *** End programmer edit section *** (Сотрудники.РабТел Get start)
                string result = this.fРабТел;
                // *** Start programmer edit section *** (Сотрудники.РабТел Get end)

                // *** End programmer edit section *** (Сотрудники.РабТел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.РабТел Set start)

                // *** End programmer edit section *** (Сотрудники.РабТел Set start)
                this.fРабТел = value;
                // *** Start programmer edit section *** (Сотрудники.РабТел Set end)

                // *** End programmer edit section *** (Сотрудники.РабТел Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ФИО Get start)

                // *** End programmer edit section *** (Сотрудники.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотрудники.ФИО Get end)

                // *** End programmer edit section *** (Сотрудники.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ФИО Set start)

                // *** End programmer edit section *** (Сотрудники.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотрудники.ФИО Set end)

                // *** End programmer edit section *** (Сотрудники.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Должности CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.SistZP2.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Должности Get start)

                // *** End programmer edit section *** (Сотрудники.Должности Get start)
                IIS.SistZP2.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Сотрудники.Должности Get end)

                // *** End programmer edit section *** (Сотрудники.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Должности Set start)

                // *** End programmer edit section *** (Сотрудники.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Сотрудники.Должности Set end)

                // *** End programmer edit section *** (Сотрудники.Должности Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Организации CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Организации CustomAttributes)
        [PropertyStorage(new string[] {
                "Организации"})]
        [NotNull()]
        public virtual IIS.SistZP2.Организации Организации
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Организации Get start)

                // *** End programmer edit section *** (Сотрудники.Организации Get start)
                IIS.SistZP2.Организации result = this.fОрганизации;
                // *** Start programmer edit section *** (Сотрудники.Организации Get end)

                // *** End programmer edit section *** (Сотрудники.Организации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Организации Set start)

                // *** End programmer edit section *** (Сотрудники.Организации Set start)
                this.fОрганизации = value;
                // *** Start programmer edit section *** (Сотрудники.Организации Set end)

                // *** End programmer edit section *** (Сотрудники.Организации Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Отделы CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Отделы CustomAttributes)
        [PropertyStorage(new string[] {
                "Отделы"})]
        [NotNull()]
        public virtual IIS.SistZP2.Отделы Отделы
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Отделы Get start)

                // *** End programmer edit section *** (Сотрудники.Отделы Get start)
                IIS.SistZP2.Отделы result = this.fОтделы;
                // *** Start programmer edit section *** (Сотрудники.Отделы Get end)

                // *** End programmer edit section *** (Сотрудники.Отделы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Отделы Set start)

                // *** End programmer edit section *** (Сотрудники.Отделы Set start)
                this.fОтделы = value;
                // *** Start programmer edit section *** (Сотрудники.Отделы Set end)

                // *** End programmer edit section *** (Сотрудники.Отделы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.SistZP2.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.SistZP2.Сотрудники));
                }
            }
        }
    }
}
