//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SistZP2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип отраб.
    /// </summary>
    // *** Start programmer edit section *** (ТипОтраб CustomAttributes)

    // *** End programmer edit section *** (ТипОтраб CustomAttributes)
    public enum ТипОтраб
    {
        
        // *** Start programmer edit section *** (ТипОтраб.ВыхДни CustomAttributes)

        // *** End programmer edit section *** (ТипОтраб.ВыхДни CustomAttributes)
        [Caption("Выходные дни")]
        ВыхДни,
        
        // *** Start programmer edit section *** (ТипОтраб.ОбычДни CustomAttributes)

        // *** End programmer edit section *** (ТипОтраб.ОбычДни CustomAttributes)
        [Caption("Обычные дни")]
        ОбычДни,
        
        // *** Start programmer edit section *** (ТипОтраб.Сверх CustomAttributes)

        // *** End programmer edit section *** (ТипОтраб.Сверх CustomAttributes)
        [Caption("Сверхурочные")]
        Сверх,
    }
}
