//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SistZP2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Удержания и вычеты.
    /// </summary>
    // *** Start programmer edit section *** (УдержИВыч CustomAttributes)

    // *** End programmer edit section *** (УдержИВыч CustomAttributes)
    [AutoAltered()]
    [Caption("Удержания и вычеты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УдержИВычE", new string[] {
            "Название as \'Название\'",
            "Сумма as \'Сумма\'"})]
    public class УдержИВыч : ICSSoft.STORMNET.DataObject
    {
        
        private double fСумма;
        
        private IIS.SistZP2.Вычет fНазвание;
        
        private IIS.SistZP2.РасчетныйЛист fРасчетныйЛист;
        
        // *** Start programmer edit section *** (УдержИВыч CustomMembers)

        // *** End programmer edit section *** (УдержИВыч CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (УдержИВыч.Название CustomAttributes)

        // *** End programmer edit section *** (УдержИВыч.Название CustomAttributes)
        public virtual IIS.SistZP2.Вычет Название
        {
            get
            {
                // *** Start programmer edit section *** (УдержИВыч.Название Get start)

                // *** End programmer edit section *** (УдержИВыч.Название Get start)
                IIS.SistZP2.Вычет result = this.fНазвание;
                // *** Start programmer edit section *** (УдержИВыч.Название Get end)

                // *** End programmer edit section *** (УдержИВыч.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УдержИВыч.Название Set start)

                // *** End programmer edit section *** (УдержИВыч.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (УдержИВыч.Название Set end)

                // *** End programmer edit section *** (УдержИВыч.Название Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (УдержИВыч.Сумма CustomAttributes)

        // *** End programmer edit section *** (УдержИВыч.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (УдержИВыч.Сумма Get start)

                // *** End programmer edit section *** (УдержИВыч.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (УдержИВыч.Сумма Get end)

                // *** End programmer edit section *** (УдержИВыч.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УдержИВыч.Сумма Set start)

                // *** End programmer edit section *** (УдержИВыч.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (УдержИВыч.Сумма Set end)

                // *** End programmer edit section *** (УдержИВыч.Сумма Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.SistZP2.РасчетныйЛист.
        /// </summary>
        // *** Start programmer edit section *** (УдержИВыч.РасчетныйЛист CustomAttributes)

        // *** End programmer edit section *** (УдержИВыч.РасчетныйЛист CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасчетныйЛист"})]
        public virtual IIS.SistZP2.РасчетныйЛист РасчетныйЛист
        {
            get
            {
                // *** Start programmer edit section *** (УдержИВыч.РасчетныйЛист Get start)

                // *** End programmer edit section *** (УдержИВыч.РасчетныйЛист Get start)
                IIS.SistZP2.РасчетныйЛист result = this.fРасчетныйЛист;
                // *** Start programmer edit section *** (УдержИВыч.РасчетныйЛист Get end)

                // *** End programmer edit section *** (УдержИВыч.РасчетныйЛист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УдержИВыч.РасчетныйЛист Set start)

                // *** End programmer edit section *** (УдержИВыч.РасчетныйЛист Set start)
                this.fРасчетныйЛист = value;
                // *** Start programmer edit section *** (УдержИВыч.РасчетныйЛист Set end)

                // *** End programmer edit section *** (УдержИВыч.РасчетныйЛист Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УдержИВычE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УдержИВычE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УдержИВычE", typeof(IIS.SistZP2.УдержИВыч));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of УдержИВыч.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУдержИВыч CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУдержИВыч CustomAttributes)
    public class DetailArrayOfУдержИВыч : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.SistZP2.DetailArrayOfУдержИВыч members)

        // *** End programmer edit section *** (IIS.SistZP2.DetailArrayOfУдержИВыч members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type УдержИВыч by index.
        /// </summary>
        /// <summary>
        /// Adds object with type УдержИВыч.
        /// </summary>
        public DetailArrayOfУдержИВыч(IIS.SistZP2.РасчетныйЛист fРасчетныйЛист) : 
                base(typeof(УдержИВыч), ((ICSSoft.STORMNET.DataObject)(fРасчетныйЛист)))
        {
        }
        
        public IIS.SistZP2.УдержИВыч this[int index]
        {
            get
            {
                return ((IIS.SistZP2.УдержИВыч)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.SistZP2.УдержИВыч dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
