//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SistZP2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Учет рабочего времени.
    /// </summary>
    // *** Start programmer edit section *** (УчетРабочВр CustomAttributes)

    // *** End programmer edit section *** (УчетРабочВр CustomAttributes)
    [AutoAltered()]
    [Caption("Учет рабочего времени")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УчетРабочВрE", new string[] {
            "Дата as \'Дата\'",
            "ОтрабЧасы as \'Отработанные часы\'",
            "ТипОтр as \'Тип отработки\'",
            "Сотрудники as \'Сотрудник\'"})]
    [MasterViewDefineAttribute("УчетРабочВрE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("УчетРабочВрL", new string[] {
            "Дата as \'Дата\'",
            "ОтрабЧасы as \'Отработанные часы\'",
            "ТипОтр as \'Тип отработки\'",
            "Сотрудники as \'Сотрудник\'"})]
    [MasterViewDefineAttribute("УчетРабочВрL", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class УчетРабочВр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private int fОтрабЧасы;
        
        private IIS.SistZP2.ТипОтраб fТипОтр;
        
        private IIS.SistZP2.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (УчетРабочВр CustomMembers)

        // *** End programmer edit section *** (УчетРабочВр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (УчетРабочВр.Дата CustomAttributes)

        // *** End programmer edit section *** (УчетРабочВр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (УчетРабочВр.Дата Get start)

                // *** End programmer edit section *** (УчетРабочВр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (УчетРабочВр.Дата Get end)

                // *** End programmer edit section *** (УчетРабочВр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчетРабочВр.Дата Set start)

                // *** End programmer edit section *** (УчетРабочВр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (УчетРабочВр.Дата Set end)

                // *** End programmer edit section *** (УчетРабочВр.Дата Set end)
            }
        }
        
        /// <summary>
        /// ОтрабЧасы.
        /// </summary>
        // *** Start programmer edit section *** (УчетРабочВр.ОтрабЧасы CustomAttributes)

        // *** End programmer edit section *** (УчетРабочВр.ОтрабЧасы CustomAttributes)
        public virtual int ОтрабЧасы
        {
            get
            {
                // *** Start programmer edit section *** (УчетРабочВр.ОтрабЧасы Get start)

                // *** End programmer edit section *** (УчетРабочВр.ОтрабЧасы Get start)
                int result = this.fОтрабЧасы;
                // *** Start programmer edit section *** (УчетРабочВр.ОтрабЧасы Get end)

                // *** End programmer edit section *** (УчетРабочВр.ОтрабЧасы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчетРабочВр.ОтрабЧасы Set start)

                // *** End programmer edit section *** (УчетРабочВр.ОтрабЧасы Set start)
                this.fОтрабЧасы = value;
                // *** Start programmer edit section *** (УчетРабочВр.ОтрабЧасы Set end)

                // *** End programmer edit section *** (УчетРабочВр.ОтрабЧасы Set end)
            }
        }
        
        /// <summary>
        /// ТипОтр.
        /// </summary>
        // *** Start programmer edit section *** (УчетРабочВр.ТипОтр CustomAttributes)

        // *** End programmer edit section *** (УчетРабочВр.ТипОтр CustomAttributes)
        public virtual IIS.SistZP2.ТипОтраб ТипОтр
        {
            get
            {
                // *** Start programmer edit section *** (УчетРабочВр.ТипОтр Get start)

                // *** End programmer edit section *** (УчетРабочВр.ТипОтр Get start)
                IIS.SistZP2.ТипОтраб result = this.fТипОтр;
                // *** Start programmer edit section *** (УчетРабочВр.ТипОтр Get end)

                // *** End programmer edit section *** (УчетРабочВр.ТипОтр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчетРабочВр.ТипОтр Set start)

                // *** End programmer edit section *** (УчетРабочВр.ТипОтр Set start)
                this.fТипОтр = value;
                // *** Start programmer edit section *** (УчетРабочВр.ТипОтр Set end)

                // *** End programmer edit section *** (УчетРабочВр.ТипОтр Set end)
            }
        }
        
        /// <summary>
        /// Учет рабочего времени.
        /// </summary>
        // *** Start programmer edit section *** (УчетРабочВр.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (УчетРабочВр.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.SistZP2.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (УчетРабочВр.Сотрудники Get start)

                // *** End programmer edit section *** (УчетРабочВр.Сотрудники Get start)
                IIS.SistZP2.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (УчетРабочВр.Сотрудники Get end)

                // *** End programmer edit section *** (УчетРабочВр.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчетРабочВр.Сотрудники Set start)

                // *** End programmer edit section *** (УчетРабочВр.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (УчетРабочВр.Сотрудники Set end)

                // *** End programmer edit section *** (УчетРабочВр.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УчетРабочВрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчетРабочВрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчетРабочВрE", typeof(IIS.SistZP2.УчетРабочВр));
                }
            }
            
            /// <summary>
            /// "УчетРабочВрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчетРабочВрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчетРабочВрL", typeof(IIS.SistZP2.УчетРабочВр));
                }
            }
        }
    }
}
